### ISSUE TITLE
Introduce string functions empty, not_empty, blank & not_blank

### ISSUE THREAD

**Issue by sdrzazga-nsd** [hashicorp/terraform-provider-assert#55]
Hi.

Please consider to add the following string functions:

1. **empty** - `string == null || length(string) == 0`
2. **not_empty** - `!empty(string)`
3. **blank** - `string == null || IsWhitespaceOnly(string)`
4. **not_blank** -  `!blank(string)`

Thank you.

**Comment by bschaatsbergen** [comment]
Hey @sdrzazga-nsd, thanks for taking the time to raise this issue—much appreciated! These are great suggestions for the assert provider.

**Comment by bschaatsbergen** [comment]
To break down the work proposed in this issue, it makes sense to start with `empty` and `not_empty` functions, as they would nicely complement the existing `null` and `not_null` functions for objects.

**Comment by bschaatsbergen** [comment]
Reopening this issue, because of the `blank` and `not_blank` functions that have not been discussed yet.

**Comment by bschaatsbergen** [comment]
We've released `empty` and `not_empty` as part of v0.13.0 of the Terraform Assert Provider.
